name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile code
        run: javac src/*.java

      - name: Run tests1
        run: java -cp src TestRunner

      - name: Build Docker image
        run: |
          docker build -t ticket-api .
          echo "Docker image built successfully"